spring.application.name=farmerapp
mongodb+srv://Adi:ADI@cluster0.phfbxfg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
jwt.secret=Zb+vo/FScM9IKdM70f3CiGkkPCMEmK0CGD7Pa1Ac5ck=
server.address=0.0.0.0