spring.application.name=farmerapp
mongodb+srv://Adi:ADI@cluster0.phfbxfg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
twilio.accountSid=ACf76c797ce170da10753052d5218b2f8b
twilio.authToken=76b1e3c539495078894d1fbc5bbbd260
twilio.phoneNumber=+18313195243
jwt.secret=Zb+vo/FScM9IKdM70f3CiGkkPCMEmK0CGD7Pa1Ac5ck=